// Code generated by protoc-gen-go.
// source: proto/pulse.proto
// DO NOT EDIT!

/*
Package requester is a generated protocol buffer package.

It is generated from these files:
	proto/pulse.proto

It has these top-level messages:
	HealthCheckRequest
	HealthCheckResponse
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthCheckRequest_ServingRequest int32

const (
	HealthCheckRequest_SETUP  HealthCheckRequest_ServingRequest = 0
	HealthCheckRequest_STATUS HealthCheckRequest_ServingRequest = 1
)

var HealthCheckRequest_ServingRequest_name = map[int32]string{
	0: "SETUP",
	1: "STATUS",
}
var HealthCheckRequest_ServingRequest_value = map[string]int32{
	"SETUP":  0,
	"STATUS": 1,
}

func (x HealthCheckRequest_ServingRequest) String() string {
	return proto.EnumName(HealthCheckRequest_ServingRequest_name, int32(x))
}
func (HealthCheckRequest_ServingRequest) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN      HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_UNCONFIGURED HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_CONFIGURED   HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_FAILVER      HealthCheckResponse_ServingStatus = 3
	HealthCheckResponse_HEALTHY      HealthCheckResponse_ServingStatus = 4
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "UNCONFIGURED",
	2: "CONFIGURED",
	3: "FAILVER",
	4: "HEALTHY",
}
var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":      0,
	"UNCONFIGURED": 1,
	"CONFIGURED":   2,
	"FAILVER":      3,
	"HEALTHY":      4,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

// Types
type HealthCheckRequest struct {
	Request HealthCheckRequest_ServingRequest `protobuf:"varint,1,opt,name=request,enum=requester.HealthCheckRequest_ServingRequest" json:"request,omitempty"`
}

func (m *HealthCheckRequest) Reset()                    { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()               {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HealthCheckRequest) GetRequest() HealthCheckRequest_ServingRequest {
	if m != nil {
		return m.Request
	}
	return HealthCheckRequest_SETUP
}

type HealthCheckResponse struct {
	Status HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,enum=requester.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
}

func (m *HealthCheckResponse) Reset()                    { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()               {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterType((*HealthCheckRequest)(nil), "requester.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "requester.HealthCheckResponse")
	proto.RegisterEnum("requester.HealthCheckRequest_ServingRequest", HealthCheckRequest_ServingRequest_name, HealthCheckRequest_ServingRequest_value)
	proto.RegisterEnum("requester.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Requester service

type RequesterClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type requesterClient struct {
	cc *grpc.ClientConn
}

func NewRequesterClient(cc *grpc.ClientConn) RequesterClient {
	return &requesterClient{cc}
}

func (c *requesterClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/requester.Requester/Check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Requester service

type RequesterServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

func RegisterRequesterServer(s *grpc.Server, srv RequesterServer) {
	s.RegisterService(&_Requester_serviceDesc, srv)
}

func _Requester_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequesterServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/requester.Requester/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequesterServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Requester_serviceDesc = grpc.ServiceDesc{
	ServiceName: "requester.Requester",
	HandlerType: (*RequesterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Requester_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pulse.proto",
}

func init() { proto.RegisterFile("proto/pulse.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x28, 0xcd, 0x29, 0x4e, 0xd5, 0x03, 0xb3, 0x85, 0x38, 0x8b, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x52, 0x8b, 0x94, 0x5a, 0x19, 0xb9, 0x84, 0x3c, 0x52, 0x13, 0x73, 0x4a, 0x32,
	0x9c, 0x33, 0x52, 0x93, 0xb3, 0x83, 0x20, 0x12, 0x42, 0x6e, 0x5c, 0xec, 0x50, 0x35, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x3a, 0x7a, 0x70, 0x3d, 0x7a, 0x98, 0xea, 0xf5, 0x82, 0x53, 0x8b,
	0xca, 0x32, 0xf3, 0xd2, 0xa1, 0xdc, 0x20, 0x98, 0x66, 0x25, 0x75, 0x2e, 0x3e, 0x54, 0x29, 0x21,
	0x4e, 0x2e, 0xd6, 0x60, 0xd7, 0x90, 0xd0, 0x00, 0x01, 0x06, 0x21, 0x2e, 0x2e, 0xb6, 0xe0, 0x10,
	0xc7, 0x90, 0xd0, 0x60, 0x01, 0x46, 0xa5, 0xad, 0x8c, 0x5c, 0xc2, 0x28, 0xe6, 0x16, 0x17, 0xe4,
	0xe7, 0x15, 0xa7, 0x0a, 0xb9, 0x70, 0xb1, 0x15, 0x97, 0x24, 0x96, 0x94, 0x16, 0x13, 0x72, 0x07,
	0x44, 0x3d, 0xcc, 0x21, 0xc1, 0x60, 0x3d, 0x41, 0x50, 0xbd, 0x4a, 0x11, 0x5c, 0xbc, 0x28, 0x12,
	0x42, 0xdc, 0x5c, 0xec, 0xa1, 0x7e, 0xde, 0x7e, 0xfe, 0xe1, 0x7e, 0x02, 0x0c, 0x42, 0x02, 0x5c,
	0x3c, 0xa1, 0x7e, 0xce, 0xfe, 0x7e, 0x6e, 0x9e, 0xee, 0xa1, 0x41, 0xae, 0x2e, 0x02, 0x8c, 0x42,
	0x7c, 0x5c, 0x5c, 0x48, 0x7c, 0x26, 0x90, 0x72, 0x37, 0x47, 0x4f, 0x9f, 0x30, 0xd7, 0x20, 0x01,
	0x66, 0x10, 0xc7, 0xc3, 0xd5, 0xd1, 0x27, 0xc4, 0x23, 0x52, 0x80, 0xc5, 0x28, 0x98, 0x8b, 0x33,
	0x08, 0xe6, 0x20, 0x21, 0x37, 0x2e, 0x56, 0xb0, 0x6b, 0x84, 0x64, 0xf1, 0x86, 0x96, 0x94, 0x1c,
	0x7e, 0x4f, 0x24, 0xb1, 0x81, 0xa3, 0xc9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x09, 0x9f,
	0x25, 0xbb, 0x01, 0x00, 0x00,
}
